Maze711/systemPayroll

FILE201/Other_Information/otherInformation.ui
FILE201/Other_Information/otherInformationModal.py

otherInformation.ui is the structure for the Other Information modal which is to be merged with personalInformation.
The design is to be revised and fixed, but the Work Experience scrolling effect is also affecting the entire scrolling of the frame.
Added files/folder:
otherInformation.ui
otherInformationModal.py
Other_Information

Other Information Modal Structure

---

FILE201/Other_Information/otherInformation.ui

From otherInformation.ui and personalInfoMODAL.ui struct which is both modal structure that been merged together in otherInformation.ui

Personal Info Struct and Other Info Struct modal merge

---

FILE201/Database_Connection/DBConnection.py
FILE201/Database_Connection/modalSQLQuery.py
FILE201/Other_Information/otherInformation.ui
FILE201/Other_Information/otherInformationModal.py
FILE201/file201_Function/modalFunction.py

Added directory such as Database_Connection, file201_function
Database_Connection where the developer can store the queries and connection of the database.
file201_Function where the developer can store such methods/functions of certain UI.
Python Files added such as DBConnection, modalSQLQuery, modalFunction,
DBConnection where a method that can be use anywhere to connect at the database
modalSQLQuery where the queries happens such as CRUD (Create, Read, Update and Delete)
modalFunction where the developer define the functionalities of UI such as the buttons
revision of some queries is on going, also we added the function button (SAVE, EDIT, ADD, REVERT)

Connected at DATABASE/Other Info Modal done

---

FILE201/Employee_List/employeeList.py
FILE201/Employee_List/employeeList.ui
FILE201/Resources/Icons/arrow-right.svg
FILE201/Resources/Icons/export.svg
FILE201/Resources/Icons/search.svg
FILE201/Resources/Icons/user-plus.svg

employeeList.ui is the file for the ui structure of employee list window
icons folder compiles all the svg icons used in the system
Some ui design may need further revisions 
Added Files/Folder:
EmployeeList
- employeeList.ui
- employeeList.py
Icons
- arrow-right.svg
- export.svg
- search.svg
- user-plus.svg

Employee List UI Structure and Added Icons

---

FILE201/Employee_List/employeeList.py
FILE201/Employee_List/employeeList.ui
FILE201/file201_Function/listFunction.py

Added the Clock Feature were it provides the current time, day, and date
Also added listFunction.py in file201_Functions folder for the functionalities of the EmployeeList.py

Added the Clock feature

---

FILE201/Database_Connection/modalSQLQuery.py
FILE201/file201_Function/modalFunction.py

The additional functionality of adding personal information is not yet finished

Added the functionality for Adding Personal Information

---

.idea/systemPayroll.iml
FILE201/Employee_List/employeeList.py
FILE201/Main.py
FILE201/Other_Information/otherInformation.ui

the objectName of otherInformation.ui change into MainWindow > personalinfoWindow

failed to connect the modal

---

FILE201/Database_Connection/modalSQLQuery.py
FILE201/Other_Information/otherInformation.ui
FILE201/file201_Function/modalFunction.py

- Insertion of Personal Information data in the database is now working but still working on the family background.
- Added New Table in the database called personal_information

Still Working on Personal Information data insertion

---

FILE201/Database_Connection/listSQLQuery.py
FILE201/Employee_List/employeeList.py
FILE201/Employee_List/employeeList.ui
FILE201/file201_Function/listFunction.py
FILE201/file201_Function/modalFunction.py

- All employees in the database is now displayed in the employeeListTable widget.
- Selection of the each employee in the table can be displayed in Employee Basic Info.
- Added listSQLQuery.py in Database_Connection folder, this file contains the SQL Query within the Employee List window.
modalFunction.py
- Added a close() so that when the employee has been added, the modal will automatically closed.

Finished Displaying and Selecting Employees in the table

---

FILE201/file201_Function/listFunction.py

USER NOW HAVE A ABILITY TO SEE THE WHOLE DESCRIPTION OF THE CHOSEN ROW FROM THE TABLE WHICH IS EMPID REFERENCE (TO BE MODIFIED)

Modified View Personal Information fetch

---

FILE201/Database_Connection/modalSQLQuery.py

- Added get_generated_employee_id function which ensures that the emp ID that is being inserted in the database is well formatted.
- insert_generated_employee_id function updates the empID in the personal_information table.

Added Generation and insertion of custom employee ID

---

FILE201/file201_Function/listFunction.py

The employee list table will refresh once the modal closes

Added Refresh table feature

---

FILE201/Database_Connection/modalSQLQuery.py
FILE201/file201_Function/modalFunction.py

- Added new column called ID for each database (except personal_information table)
- Fix the bug on inserting suffix

Added new column called ID for each database (except personal_information table)

---

FILE201/Employee_List/employeeList.py
FILE201/file201_Function/excelExport.py

- The Excel exporter fetches employee data from a database and saves it to an Excel file. It uses a function to retrieve the data and column names, opens a file dialog for the user to specify the save location, and then creates an Excel file using the `pandas` library.

ExcelExporter

---

TimeKeeping/dialogImporter.ui
TimeKeeping/dialogLoader.py

Created a function that always filters when importing a (DAT, TXT) Files to discard the unnecessary files.
Created a logger checks if the data from the imported file is correct (for debugging only)

Importing and Logger works

---

FILE201/Employee_List/employeeList.py
FILE201/file201_Function/excelExport.py
TimeKeeping/timeLogger/timeLog.py
TimeKeeping/timeLogger/timeLog.ui

- The updated exporter retrieves data from multiple tables (personal_information, family_background, list_of_id, work_exp, educ_information, tech_skills) and exports this data into different sheets within the same Excel file. Each sheet corresponds to one of the tables, allowing for a well-organized export of all relevant employee information.
-  Updated 'processContent' method to categorize time entries (code_1, code_2, code_3) into a new field "sched" ("Time IN", "Time OUT", or "Unknown"), improving data categorization and clarity.
- Modified populateTable method to center-align all data within the QTableWidget, ensuring a neat and visually appealing display of imported data for better user readability.

Updated Exporter

---

TimeKeeping/timeCardMaker/search.svg
TimeKeeping/timeCardMaker/timecard.ui

Just deleted the SVG from timeCardMaker directory, then use the search svg from FILE201/RESOURCES

SVG File Directory Changed

---

FILE201/file201_Function/listFunction.py

Fix the bug on clearFunction were it unselects the current row to prevent view btn from entering

Bug fix on clearFunction

---

FILE201/Other_Information/personalInformation.ui
TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeCardMaker/timecard.ui
TimeKeeping/timeLogger/timeLog.py
TimeKeeping/timeLogger/timeLog.ui

TIME IN AND TIME OUT FILTERED CORRECTLY ACCORDING TO THE BioNum.
Also from the title head DATE FROM: AND DATE TO: is also getting their fetched data from timelogger.
FONT_LOADER IS AFFECTING THE QCalendarWidget (Can't fix)
MISSING DATA EmpNumber AND EmpName.

Time Card TIME IN AND TIME OUT DATA fetched

---

FILE201/Employee_List/employeeList.py

JUST ADJUSTED THE EMPLOYEE_LIST IMPORTER QUERY

FROM EXCEL TO DATABASE IMPORTER

---

FILE201/Database_Connection/listSQLQuery.py
FILE201/file201_Function/listFunction.py

Updated fields and removed some QWidgets

Updated Fetching Data

---

TimeKeeping/Schedule.ui
TimeKeeping/checkSched.py
TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeCardMaker/timecard.ui
dist/FILE201/file201_Function/listFunction.py

New Modal 'CheckSched' connected into timeCard

Check Schedule Dialog

---

FILE201/Database_Connection/DBConnection.py
FILE201/Employee_List/employeeList.py
TimeKeeping/Schedule.ui
TimeKeeping/checkSched.py
TimeKeeping/timeCardMaker/timecard.ui
TimeKeeping/timeLogger/timeLog.ui
TimeKeeping/timeSheet/TimeSheet.ui
TimeKeeping/timeSheet/timeSheet.py

newly created modal 'timeSheet' and redesigned 'Schedule' modal

Newly Created UI

---

.idea/encodings.xml
TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeLogger/timeLog.py

Updated TIME LOGGER WHICH IS FINDING THE surname, firstname and mi from personal_information and making them concatenated to make a whole name then giving it to the timeCard.

Time Logger and Time Card updated

---

FILE201/Employee_List/employeeList.py
MainWindow.py
TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeCardMaker/timecard.ui
TimeKeeping/timeLogger/timeLog.py
TimeKeeping/timeSheet/TimeSheet.ui
TimeKeeping/timeSheet/timeSheet.py

- Additional Hovered Button in MainWindow UI
- QTableWidget sets into QHeaderView = Fixed (timeLog, timeCard, employeeList, timeSheet)

Hover Button

---

TimeKeeping/timeLogger/timeLog.py

From the past code, instead of sending the filtered data and matching the latest transdate with the wrong Check In and Check Out, I created a combined_data which corresponds a unique set of data with a key of bio_no and trans_date.
from that combined_data it combing this list of table or data:

Working Duplicated BioNum and Transdate to timecard

---

MainWindow.py
TimeKeeping/datImporter/dialogImporter.ui
TimeKeeping/datImporter/dialogLoader.py

- Time Keeping button Functionalities has been disabled and transferred into Time Logger button 
- The Imported Data Loading Bar It displaying a progress indication while importing files and also reducing perceived lag for the system.

Import Data Processing

---

.idea/systemPayroll.iml
TimeKeeping/datImporter/dialogImporter.ui
TimeKeeping/datImporter/dialogLoader.py
TimeKeeping/timeLogger/timeLog.ui

- Splits the file into chunks, saves them in a temporary folder, and updates the progress bar and it combine the content of these chunk files and pass it to the timelogger class.

Chunking Data

---

TimeKeeping/datImporter/dialogImporter.ui
TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeCardMaker/timecard.ui
TimeKeeping/timeSheet/TimeSheet.ui
TimeKeeping/timeSheet/timeSheet.py

ADDED THIS COLUMNS
CHECK-IN, CHECK-OUT, OVERTIME HOURS AND MACHINE CODE.

UPDATED UI FOR TIMESHEET

---

TimeKeeping/schedValidator/Schedule.ui
TimeKeeping/schedValidator/checkSched.py
TimeKeeping/timeCardMaker/timeCard.py

- Population of data within Schedule Dialog by clicking each row is now working.
- The getTotalHoursWorked function computes the timein and time out data to retrieve the number of hours worked by the employee.
- getTypeOfDate function retrieves the dateType from type_of_dates database

Population of Data within Schedule Dialog

---

TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeSheet/TimeSheet.ui
TimeKeeping/timeSheet/timeSheet.py

- TimeSheet Update from MainWindow to Dialog and make the header fix and data in center of its cell.

Passing dataMerge to TimeSheet

---

TimeKeeping/schedValidator/checkSched.py
TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeSheet/TimeSheet.ui
TimeKeeping/timeSheet/timeSheet.py

Moving getTotalHoursWorked from chkSched into timecard since it will be use by timeSheet

Total of working hours is pass into TimeSheet

---

MainWindow.py
TimeKeeping/dateChange/dateChange.py
TimeKeeping/dateChange/datechange.ui

- The form allows changing the holiday date only if 'holidayIsMovable' is set to 1 in the database; if it's set to 0, the date change option is disabled.

Date Change

---

TimeKeeping/schedValidator/Schedule.ui
TimeKeeping/schedValidator/checkSched.py

- getHolidayName function retrieves the holidayName in type_of_date database based on the attendance date of an employee
- Adjusted some space and size of ui elements within schedule.ui

Added Holiday Name in Schedule

---

FILE201/Employee_List/employeeList.py
TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeLogger/timeLog.py
TimeKeeping/timeSheet/timeSheet.py

FROM TIMELOG WE ALREADY COMPUTE (DIFFERENCE) THE SCHED_IN AND SCHED_OUT AND CONCATENATE THEM TOGETHER TO MAKE A SCHE_NAME AND PLACE THEM INTO SCHEDULE COLUMN UPON CREATING TIMECARD
IN TIME CARD WE PLACE THE getTypeOfDate FUNCTION TO COMPARE THE DATE FROM TRANS_DATE TO DATE IN DATABASE TIMEKEEPING UNDER TYPE_OF_DATE.
The image/code above is passed to the timesheet 
The image/code above is computing the difference of the Sche_name and hoursWorked.
The image/code above is working search for BioNum in TimeSheet.
The image/code above is passing the data in their columns by index.
Lastly we updated the file201 database especially the sche_name, instead of containing both we split to sched_in and sched_out also the importer updated.

Working Ordinary Day Column

---

MainWindow.py
TimeKeeping/timeCardMaker/filter.py
TimeKeeping/timeCardMaker/filter.ui
TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeCardMaker/timecard.ui

- The filter functionalities allow users to filter time card data based on the AM/PM selection for check-in and check-out times, and retain these filter settings for future sessions

TEMPORARY FILTER MODAL

---

TimeKeeping/timeCardMaker/filter.py
TimeKeeping/timeCardMaker/filter.ui
TimeKeeping/timeCardMaker/timeCard.py

The missing function checks for rows where either the check-in or check-out time is marked as "Missing" and includes those rows in the filtered results if the show_missing flag is enabled.

Missing Filter

---

FILE201/file201_Function/listFunction.py
MainFrame/Database_Connection/listSQLQuery.py

> Make the search only accept EMPL_ID, SURNAME, FIRSTNAME AND MIDDLE INITIAL
> MAKE THE TABLE ROWS ASCENDING (ALPHABETICAL)

UPDATED FETCHING IN EMP_LIST TABLE

---

TimeKeeping/paytimeSheet/paytimeSheet.py
TimeKeeping/timeLogger/timeLog.py

- Added fetch_all_holidays function in timeLog where it retrieves all the holiday dates in type_of_dates table
- The image below shows a dictionary of number of present holidays that a certain employee attended.

Holiday column in paytimeSheet is now working

---

FILE201/file201_Function/excelImporter.py
TimeKeeping/payTrans/payTransLoader.py
TimeKeeping/payTrans/paytrans.ui
TimeKeeping/paytimeSheet/paytimeSheet.py
TimeKeeping/paytimeSheet/paytimesheet.ui
TimeKeeping/timeLogger/timeLog.py

- Added a BioNum column in PayTrans
- Added a button in PayTimeSheet to create or open the paytrans
- From PayTimeSheet it will pass the selected_data in PayTrans and adding to certain columns
PS: I need to verify the BioNum and Empl_ID so that I can fetch the other information from database into the UI/System.
- Also again updated importer since the system we will use the HR FILE201 which means updated columns, import query and database.

Some Adjustment in UI and fetching and receiving

---

TimeKeeping/payTrans/payTransLoader.py
TimeKeeping/paytimeSheet/paytimeSheet.py
TimeKeeping/timeLogger/timeLog.py

- Some adjust in query to get the empl_id from database (timelog.py)
- From payTimeSheet.py I created a Excel reader which reads the column EMPL_ID and RATE
- The code below is comparing the empl_id and bio_num which is coming from DAT file and getting their sum.
- We're removing the first two digits from empl_id since that's the instructions and to have relation in DAT bio_num (Ex: 1755557 will be 55557)
- We're printing and logging the sum of them all and getting also the rate data from rate column
- We're also giving the rate in rate_item so that we can see who have relation and who have missing rate data
- Missing rate data comes from 0 or no relation empl_id and bio_num

Daily Rate data from file201

---

Logger_config.py
MainWindow.py
TimeKeeping/datImporter/dialogLoader.py
TimeKeeping/dateChange/dateChange.py
TimeKeeping/schedValidator/checkSched.py
TimeKeeping/timeCardMaker/filter.py
TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeLogger/timeLog.py
TimeKeeping/timeSheet/timeSheet.py
TimeKeeping/timekeeping_Function/timekeepingFunction.py

This refactor consolidates various functions into the 'timekeepingFunction.py' module to Improved code readability and maintainability by reducing repetitive code.

Refactor Repetitive Functions

---

FILE201/Employee_List/employeeList.py
FILE201/Other_Information/otherInformationModal.py
FILE201/file201_Function/excelExport.py
FILE201/file201_Function/excelImporter.py
FILE201/file201_Function/listFunction.py
FILE201/file201_Function/modalFunction.py
FILE201/file201_Function/pieGraph.py
MainFrame/Database_Connection/DBConnection.py
MainFrame/Database_Connection/listSQLQuery.py
MainFrame/Database_Connection/modalSQLQuery.py
MainFrame/Resources/lib.py
MainFrame/fontLoader.py
MainFrame/systemFunctions.py
MainWindow.py
TimeKeeping/datImporter/dialogLoader.py
TimeKeeping/dateChange/dateChange.py
TimeKeeping/payTimeSheetImporter/payTimeSheetImporter.py
TimeKeeping/payTrans/payTransLoader.py
TimeKeeping/paytimeSheet/paytimeSheet.py
TimeKeeping/schedValidator/checkSched.py
TimeKeeping/timeCardMaker/timeCard.py
TimeKeeping/timeLogger/timeLog.py
TimeKeeping/timeSheet/timeSheet.py

In MainFrame\Resources we created a lib.py for global call of libraries we are using in the application

Global Library created

---

MainFrame/Resources/lib.py
MainFrame/systemFunctions.py
MainWindow.py

Handles the duration of the application startup

Maximize the load of application

---

MainFrame/file_import.log
MainFrame/systemFunctions.py
MainWindow.py
TimeKeeping/payTimeSheetImporter/payTimeSheetImporter.py
TimeKeeping/paytimeSheet/paytimeSheet.py
TimeKeeping/schedValidator/checkSched.py
TimeKeeping/timeCardMaker/filter.py
TimeKeeping/timeCardMaker/timeCard.py
application_duration.log
dist/TimeKeeping/timeLogger/timeLog.py

Added a logger function in Payroll and Timekeeping, also refactoring the file_import.log into Mainframe directory
Timekeeping
- checkSched
- filter
- timeSheet
Payroll
- paytimeSheet
- payTimeSheetImporter

LoggerFunctionInPayroll

---

MainFrame/Database_Connection/DBConnection.py
MainFrame/Resources/lib.py
MainFrame/file_import.log
TimeKeeping/datImporter/dialogLoader.py
application_duration.log

- An immediate solution for DAT file importer is to append/merge together the same date for example when importing a new DAT file we created a importChunkToDatabase function that will allow to insert and update in their existing table.
- If the date doesn't found in existing table it will create a new table for it then insert the data
- We also made it better for holding and processing data.
- We also disable the closing and clicking the import while in processing mode.
PS: The code right now is kinda mess up and need some improvement for progression bar because it's kinda slow and sucks

Updated dat importer

---

MainFrame/Database_Connection/DBConnection.py
MainFrame/Resources/UI/paytimesheet.ui
MainFrame/file_import.log
MainFrame/systemFunctions.py
TimeKeeping/payTrans/payTransLoader.py
TimeKeeping/paytimeSheet/paytimeSheet.py
application_duration.log

- The image above especially the self.original_data = data is an indication for the original state of the table which if there's no input anymore in the txtSearch. it will be called using (image below)
- To return to its original state.
- We also compare the Bio Num (PaytimeSheet) and Empl_ID (FILE201) to get the employee rate (this will need validation to sure all employees do have a rate and correcting matching)
- We're removing the first 4 digits in Bio Num and checking if it's the same in Empl_ID

Working match bioNum and Empl_ID and Search Bar

---

FILE201/file201_Function/excelExport.py
FILE201/file201_Function/listFunction.py
MainFrame/Database_Connection/modalSQLQuery.py
MainFrame/Resources/UI/datechange.ui
MainFrame/Resources/UI/dialogImporter.ui
MainFrame/Resources/UI/employeeList.ui
MainFrame/Resources/UI/paytrans.ui
MainFrame/Resources/UI/personalInformation.ui
MainFrame/Resources/lib.py
TimeKeeping/dateChange/dateChange.py

- Changing the Title Name of every modal
- Updated modalSQLQuery and listFunction in File201 to fetch tables and fields based on the updated File201 database.
- Redesigned the Date Change UI: added an "Add" button to insert new holidays, which disables the "Update" button to prevent modifications to existing holidays. This adds a new blank row in the holiday combo box for inputting a new holiday name. Changed dateType from QLineEdit to a combo box, which updates the database when the "Save" button is clicked.
- Incomplete excelExport function; needs a logger to collect INFO and ERRORS.

FILE201 Validations

---

TimeKeeping/datImporter/dialogLoader.py

FileProcessor is the responsible to import the DAT file into database.
- processContent responsible for processing the data inside of the DAT file
Code Below is on for responsible to splitting the date and time and giving their own indexes
self.data['date'] = self.data['date_time'].str.split(' ').str[0]
self.data['time'] = self.data['date_time'].str.split(' ').str[1]
- The code above is responsible for determining the schedule in that data.
- The code above is responsible to create the custom name which is FROM_YYYY_MM_DD_TO_YYYY_MM_DD

Updated FileProcessor

---

MainFrame/Resources/Icons/key.svg
MainFrame/Resources/Icons/lock.svg
MainFrame/Resources/Icons/log-out.svg
MainFrame/Resources/Icons/mail.svg
MainFrame/Resources/Icons/user-name.svg
MainFrame/Resources/UI/Main.ui
MainFrame/Resources/UI/paytrans.ui
MainFrame/Resources/lib.py
TimeKeeping/payTrans/payTransLoader.py

- Added new svg icons in Icons folder within MainFrame/Resources
- Added email sender feature for sending payroll details to each employee in paytrans.
- The function prepare_email_body prepares the contents of the email (shown on image below).
- send_email function will handles each single email to be sent (shown on image below).
NOTE: Within sendToEmail function, there are few notice (comments) that needs to be considered, since this feature is under testing phase and not yet complete. Further revisions in the future will be implemented.
- For testing this feature, fill out all the email credentials shown above (based on your own gmail and generated password)
- The image above shows a tentative data that will be sent through email. In this case, only 3 employee data will be processed.

Added email sender and new icons

---

MainFrame/Resources/UI/timecard.ui
TimeKeeping/datImporter/dialogLoader.py
TimeKeeping/timeCardMaker/timeCard.py

Altered the UI of TimeCard which can be seen now after a import of DAT file, 
The code above is responsible for reading the entire database table and then the re.compile means it will remove the from_ into the table name to get the 4 integer digits to get the year
Populate_date_combo_boxes and populate_time_list_table will be change, no description now.
GOAL: Change the syntax for DAT import

Time Card Working

---

TimeKeeping/datImporter/dialogLoader.py
TimeKeeping/timeCardMaker/timeCard.py

The importChunkToDatabase method manages the import of chunked data into the LIST_LOG_IMPORT database. It performs the following steps:
- Database Connection: Establishes a connection to the LIST_LOG_IMPORT database.
Table Creation: Creates a table named Table_YYYY_MM if it does not already exist.
- Data Insertion/Update: Inserts data into the table, or updates existing records if a duplicate entry is found, particularly updating the sched field.
- File Cleanup: Deletes the chunk file after processing to maintain a clean environment.
populate_year_combo_box:
- Fills the year combo box (yearCC) with year-month combinations derived from table names in the LIST_LOG_IMPORT database.
populate_date_combo_boxes:
- Updates the date combo boxes (dateFromCC and dateToCC) based on the selected …

Dialog update and Time card working

---

FILE201/file201_Function/excelExport.py
FILE201/file201_Function/listFunction.py
FILE201/file201_Function/modalFunction.py
MainFrame/Database_Connection/modalSQLQuery.py

- Partition the addr1 field into specific fields based on the UI (Street, Barangay, City, Zipcode) and update the database by renaming empID to empl_id. Convert the list of ID fields into a string and fetch it in a query.
- Recreated the "Export to Excel" function in File201 to export a single sheet instead of multiple sheets for each SQL table. The function copies the table DataFrame from the data_dict dictionary into a new combined_df.
It iterates through data_dict, merging each DataFrame (except "Personal Information") with combined_df using empl_id as the primary key in a left join. 
After merging, it prefixes non-empl_id columns with the table/sheet name to avoid conflicts. 
The final combined_df is written to an Excel sheet named "Employee Data".

ReCreated File201 Excel Exporter

---

MainFrame/Database_Connection/DBConnection.py
MainFrame/Database_Connection/user_auth.py
MainFrame/TimeKeeping/datImporter/dialogLoader.py
MainFrame/TimeKeeping/payTimeSheetImporter/payTimeSheetImporter.py
MainFrame/TimeKeeping/paytimeSheet/paytimeSheet.py
MainWindow.py

- Refactored user authentication and authorization codebase from MainWindow.py to Database_Connection/user_auth.py to make it readable and easy to maintain.
- Fixed the logout feature issue where visible modals are still running even after logging out.
- Made the modal importers and date change modal from show() to .exec_() to prevent the main window from over lapping those modals.
- created test_databases_connection function to DBConnection for database testing and to prevent the application from opening whenever database connection was lost. (added a QMessagebox as well to notify the user about connection lost)

Refactored user authentication and Fix log out issue

---

MainFrame/Resources/UI/TimeSheet.ui
MainFrame/Resources/UI/paytimesheet.ui
MainFrame/Resources/UI/timecard.ui
MainFrame/TimeKeeping/dateChange/dateChange.py
MainFrame/TimeKeeping/timeCardMaker/timeCard.py

Search Function
- Connected the search box's textChanged signal to a new search_bio_num method.
- Stored original table data in self.original_data for easy restoration.
- Implemented search_bio_num to filter data based on user input.
- Created populate_table_with_data to efficiently update the table with filtered or original data.

Search Function (Timecard)

---

MainFrame/FILE201/file201_Function/excelImporter.py
MainFrame/TimeKeeping/datImporter/dialogLoader.py

Since the data we have is trash, we decided to mix them up the ntp and file201 to build the Excel column header to have proper data inside of the database.
NOTE: IT'S STILL ON PROCESS.

Excel Importer working

---

MainFrame/Resources/UI/TimeSheet.ui
MainFrame/TimeKeeping/timeCardMaker/timeCard.py

Fetched selected row data
- Update button doesn't have function
- Employee name can't fetch because no relation to the timcard and file201

Incomplete CheckSched

---

MainFrame/FILE201/file201_Function/excelExport.py

Removed the table name in the fields and removed the dublicate columns with numeric suffix

excelExportUpdate

---

MainFrame/FILE201/Other_Information/otherInformationModal.py
MainFrame/FILE201/file201_Function/excelImporter.py
MainFrame/Resources/UI/Main.ui
MainFrame/Resources/UI/employeeList.ui
MainFrame/Resources/UI/personalInformation.ui
MainWindow.py

- The cursor is only defined inside the with create_connection('FILE201') as connection, which is not executed when no file is selected. The finally block is still executed, which tries to close the cursor variable, causing the error.
- By initializing cursor and connection to None, the finally block will not try to close undefined variables, preventing the crash.

Fixed Import Crash

---

MainFrame/Database_Connection/user_auth.py
MainFrame/systemFunctions.py

- Added a custom Exception Handler that can be use to raise an Exception during lost of database connection. which prevents the application from exiting if it occurs (shown on image above.)
- The image above shows an example of its usage
NOTE: The implementation of this error handler is only been used in login/signup/reset password (in user_auth.py) pages, and will about to use in all database queries in the entire application.

Database Connection Error Handler (Unfinished)

---

MainFrame/Resources/UI/timecard.ui
MainFrame/TimeKeeping/timeCardMaker/timeCard.py
MainFrame/TimeKeeping/timeSheet/timeSheet.py
MainWindow.py

- We just fetch the schedule from emp_posnsched also the employee name
- We also populate the "SELECT COST CENTER" Drop Down
- Removed the "SELF" in BugReportModal

Working Employee name and Schedule

---

MainFrame/Resources/UI/dialogImporter.ui
MainFrame/Resources/UI/showNotification.ui
MainFrame/Resources/UI/timecard.ui
MainFrame/TimeKeeping/datImporter/dialogLoader.py
MainFrame/notificationMaker.py

- We transferred the FileProcessor and Progression Bar from DialogLoader into NotificationMaker.
- We also created a function that will check if the database contains a table, once a database have a table upon reading we should allow the button to direct into the timecard.

Deployed Processor and updated dialogLoader

---

MainFrame/Database_Connection/modalSQLQuery.py
MainFrame/Database_Connection/user_auth.py
MainFrame/FILE201/file201_Function/listFunction.py
MainFrame/FILE201/file201_Function/modalFunction.py
MainWindow.py

- Implementation of Database Disconnection Error Handler in add, edit, display and search feature (except import and export) under File201
- Added a QMessageBox Question before saving employee data (Shown in image below)

Implemented Database Disconnection Error Handler in File201

---

MainFrame/Resources/UI/timecard.ui
MainFrame/TimeKeeping/timeCardMaker/timeCard.py

- Added an if statement for each button (filter, and proceed timesheett) before proceeding with its main functionalities
-  if the if statement is met its condition it won't allow the whole function to proceed but instead pop out a QMessageBox indicating to select a specific criteria first in order to be use.
In Filter button:
In proceed timesheet:
- Added a export button in timecard.ui

Selection validation in buttons filter, and proceed timesheet

---

MainFrame/FILE201/Employee_List/employeeList.py
MainFrame/FILE201/file201_Function/excelExport.py
MainFrame/Resources/UI/deduction.ui
MainFrame/Resources/UI/personalInformation.ui
MainFrame/Resources/lib.py
MainFrame/systemFunctions.py

EXPORT FUNCTION IN EMPLOYEELIST.PY
- The new features of Excel Exporter are now exporting employee data to Excel or CSV files. 
- Depending on the file extension (.csv, .xls, .xlsx), it calls the appropriate export function (export_combined_csv, export_combined_xls, or export_combined_xlsx).
- The export_data_in_chunks is used to combine and export the data and the data from different tables is concatenated horizontally (pd.concat) to form a single DataFrame which depending on the file format, the data is either saved as a CSV or an Excel file in chunks of chunksize rows at a time.
FETCHING DATA IN EXCELEXPORT.PY
- It iterates through a predefined list of table names and for each table, it executes a SQL query to select all data (SELECT * FROM {table_name}) and then stores the result in a …

Unfixed Excel Exporter

---

MainFrame/TimeKeeping/timeCardMaker/timeCard.py

- We just connected the btnExport that we have in the UI
- And added the excel_to_excel function

Under timecard added export to excel

---

MainFrame/FILE201/Employee_List/employeeList.py
MainFrame/FILE201/file201_Function/excelExport.py

We just added the showNotification.ui which handles the progression bar

working in background for file201

---

MainFrame/TimeKeeping/paytimeSheet/paytimeSheet.py
MainFrame/TimeKeeping/paytimeSheet/storeDeductionLoader.py

- Refractor the code of storing all the deduction data from paytimeSheet.py to storeDeductionLoader.py
- Added a progress bar for visualization while importing all the data into deductions table

Added storeDeductionLoader for storing deduction

---

MainFrame/FILE201/file201_Function/listFunction.py
MainFrame/Resources/UI/personalInformation.ui

TABLE DONE FETCHING
- emp_info
- family_background
- emp_list_id
PS. Have an error in fetching the i.taxstat

Unfinished fetching the otherinformationmodal_view

---

MainFrame/Resources/UI/timecard.ui
MainFrame/Resources/lib.py
MainFrame/TimeKeeping/timeCardMaker/timeCard.py

- Added a caution message where it will not proceed or proceed base on the user-selected answer, if YES is selected it will continue to update the Time_in and Time_out based on dept_name

Updating of DEPT_NAME under POSNSCHED

---

MainFrame/Resources/UI/paytrans.ui
MainFrame/TimeKeeping/payTrans/payTransLoader.py

- Added new function in payTransLoader.py that will insert all the deduction of the employee based on deductions table
- Under populateTransTable function they key and value pairs for Pay Ded has been added to populate the table upon insertion

Added Insertion of Deduction in payTransTable

---

MainFrame/FILE201/file201_Function/excelExport.py
MainFrame/TimeKeeping/payTrans/payTransLoader.py

- Data rows relation successfully
- Removed the duplicate fields/columns
- Successfully importing the exported excel

Excel Export Successfully Importing

---

MainFrame/Resources/UI/dialogImporter.ui
MainFrame/TimeKeeping/datImporter/dialogLoader.py
MainFrame/TimeKeeping/payTimeSheetImporter/payTimeSheetImporter.py

- Still struggling with the population of the already stored data in the database to the ui table in Deduction table ui
- There's a problem within the session where in the additional button (which is the btnViewDeduction) is not showing until you exit and relogged into paymaster2.

Unfinished population of stored deduction

---

MainFrame/Resources/UI/Schedule.ui
MainFrame/Resources/UI/TimeSheet.ui
MainFrame/Resources/UI/datechange.ui
MainFrame/Resources/UI/filter.ui
MainFrame/Resources/UI/payDeduction.ui
MainFrame/Resources/UI/paytimesheet.ui
MainFrame/Resources/UI/personalInformation.ui
MainFrame/Resources/UI/timecard.ui
MainWindow.py

UI Adjustments

---

MainFrame/TimeKeeping/payTrans/payTransLoader.py
MainFrame/TimeKeeping/payroll_functions/payTransFunctions.py

- Move all paytrans functions to payTransFunctions.py under payroll_functions folder

Refactoring all payTrans functions into payTransFunctions.py

---

MainFrame/FILE201/file201_Function/modalFunction.py
MainFrame/Resources/UI/deduction.ui
MainFrame/Resources/UI/paytimesheet.ui
MainFrame/Resources/UI/personalInformation.ui

Done Fetching but have some errors
"An error occurred: 'QLineEdit' object has no attribute 'currentText' "

Fetching Add Employee

---

MainFrame/TimeKeeping/timeCardMaker/timeCard.py
MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py

We just added a new function named on_row_double_clicked to ensure the data of that row we double click will be transfer at check schedule
PS: Filter function still doesn't working correctly

Double clicking for row in timecard

---

MainFrame/Resources/UI/TimeSheet.ui
MainFrame/Resources/UI/payDeduction.ui
MainFrame/Resources/UI/paytimesheet.ui
MainFrame/Resources/UI/paytrans.ui
MainFrame/Resources/UI/timecard.ui

UI Changes

---

MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py

- Instead of using QTime.hour(), QTime.minute(), QTime.second(), we use a datetime.hour, datetime.minute, datetime.second a built-in function within the python application to ensure the computation of hours worked of the employee.

Total hours worked done

---

MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py

- We assigned a self.parent.original_data = time_data which the time_data is the dictionary holds the data of the selected year and date which is giving to the populating a table.

Exporting of time card working

---

MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py

- Just passing the populated time_date to populate_table_with_data

Search bio num fixed

---

MainFrame/Payroll/payTimeSheetImporter/payTimeSheetImporter.py
MainFrame/Payroll/payTrans/payTransLoader.py
MainFrame/Payroll/payroll_functions/payrollImporterFunctions.py
MainFrame/Payroll/paytimeSheet/paytimeSheet.py

- Search Bio Number function is now working in all payroll frames.
- refactoring all paytimeSheetImporter functions in payrollImporterFunctions.py

All search function is now working in payroll

---

MainWindow.py
main_functions.py

- The functions have been moved to the `MainWindowFunctions` class, which `MainWindow` inherits, keeping the main class clean and focused on initialization and setup.

Cleaning MainWindow

---

MainFrame/Database_Connection/user_auth.py

- To ensure that the username inputs in landing page are case-sensitive, I added "BINARY" to every sql query on username in user_auth.py.

Case-sensitive username input validation

---

MainFrame/Resources/UI/TimeSheet.ui
MainFrame/TimeKeeping/timeSheet/timeSheet.py
MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py

- Initially, dataMerge was a list that stored each row's data individually, even if the BioNum was repeated. This meant that if a BioNum appeared multiple times in the table, it would be included as separate entries in dataMerge.
Updated Approach (aggregated_data as a dictionary):
- Now, aggregated_data is a dictionary where each BioNum acts as a unique key. This allows us to aggregate data for each unique BioNum across all rows. The idea is to combine all the records for a specific BioNum into a single entry, summing up their work hours and counting the total days worked.

Updated UI and Population for time sheet

---

MainFrame/Database_Connection/modalSQLQuery.py
MainFrame/Resources/UI/employeeList_Accountant.ui
MainFrame/Resources/UI/personalInformation.ui

- I removed the two work experiences since they are not ideal for the application. we are focusing on the accountant side.
- I added the ID List from Personal Information to employeeList_Accountant
- I added a new query that produces the notification sender when the application's HR added a new employee since the Accountant/Paymaster will be the one managing their details.

Updated Employee List, Added new query

---

MainFrame/Database_Connection/notification_listener.py
MainWindow.py

**IMPORTS:**
- Import flask and it's essential to use it the API of PORT ( request, jsonify )
- Import the requests library to make HTTP requests.
- Import the time library for handling time-related operations.
- @app.route('/notifications', methods=['GET']): Defines a route for the endpoint /notifications that accepts GET requests.
last_checked = int(request.args.get('last_checked', 0)): Retrieves the last_checked parameter from the query string (default is 0).
Connects to the MySQL database and executes a query to fetch notifications where created_at is greater than last_checked. created_at is a timestamp column that should be in your table schema.
Returns the notifications as a JSON response using jsonify.

Flask notification deployment

---

MainFrame/Payroll/payroll_functions/payTransFunctions.py

- ImportFromExcel function gets the chosen deduction excel file (that was created by PayMaster2) of the user to processed and inserted in the table.
**Two classes has been added within payTransFunctions.py**
- The image shown below is a class that contains the process of importing the deduction from the excel file.
- The image shown below is a class that contains the UI loader progression bar for the visualization of the imported excel file.

ImportFromExcel function in payTrans is now working

---

MainFrame/Payroll/payroll_functions/payComputations.py
MainFrame/Payroll/payroll_functions/payTransFunctions.py
MainFrame/Payroll/payroll_functions/payrollImporterFunctions.py
MainFrame/Payroll/payroll_functions/paytimeSheetFunctions.py

- From payrollImporterFunctions.py we revise the FileProcessor class to accept both old and new Excel file formats since it's having an error when reading an XLS extension that is old formatted Excel.
- We should slice 2 integers in bionum when using a BOOK1 Excel file and 3 when using the paytimeSheet Excel file. However, this should be a fixed value since we're creating the paytimesheet file from timekeeping.
- Created the lateComputation and undertimeComputation.
- Passing the computed value of LATE and UNDERTIME

Late and Undertime computation

---

MainFrame/Resources/UI/paytimesheet.ui

Added a indication box

---

MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py
Revision for systemPayroll.txt

- Crash Bug while searching bio number in TimeCard is now fixed
- Created an instance of populateList class in order to use its population function

Search Field in Time Card is now working properly

---

MainFrame/FILE201/file201_Function/excelImporter.py
Revision for systemPayroll.txt

- Fix appending empid in posnsched table after an excel file was imported in file201
**Importing Progress Loader Feature**
- Added 2 classes in excelImporter.py that handles the progress loader of excel importer

Fix appending empid in posnsched table after import

---

MainFrame/Payroll/payroll_functions/payrollImporterFunctions.py

- Created a column mapping to handle different column names
- Using the standardize_header method it validates the imported excel column headers for required columns

PayrollImportColumnMapping

---

MainFrame/Database_Connection/notification_listener.py
MainFrame/Payroll/paymaster_Employee/payaddEmployee.py
MainFrame/Payroll/paytimeSheet/paytimeSheet.py
MainFrame/Resources/UI/employeeList_Accountant.ui

- We created the function for the empIDBtn which is a QT Component button.
- This thing will be the one fetching the employee NAME within the database, still using a flask since we're relying on the kinda live-server update for the button, it will increment itself when there's a new ROW added
- First, we call the total notification count in notification_listener.py and then return it as a count.
- Then add_employee_button creates the button for the employee ID, which has a fixed sizes and position.
- The load_existing_employee function is responsible for giving the count of the button to add_employee_button to create a button.
- Second, when we clicked the existing empIDBtn it's start to fetch the surname, firstname and mi to fetch it to component label named as empNameTxt

Fetching employee details from notification

---

MainFrame/Database_Connection/modalSQLQuery.py
MainFrame/FILE201/Other_Information/otherInformationModal.py
MainFrame/FILE201/file201_Function/listFunction.py
MainFrame/FILE201/file201_Function/modalFunction.py
MainFrame/Resources/Icons/upload-photo.svg
MainFrame/Resources/UI/personalInformation.ui
MainFrame/Resources/lib.py

- Added an Employee Profile Image uploader in file201 add and view modal:
- Added a ''emp_images' table in NTP_EMP_LIST database
- The following functions in modalFunction will handle the process of uploading an image in order to store and retrieve it from the emp_images table in the NTP_EMP_LIST database:
- Also added a feature within the img uploader where the user can only upload an image ONE AT A TIME ONLY, if it manages to capture a data image from the database, the uploader button will disappear:
NOTE: 
The image uploader can only be used to newly inserted employee yet.

Employee Profile Image uploader is now working

---

MainFrame/Database_Connection/notification_listener.py
MainFrame/Payroll/paymaster_Employee/payaddEmployee.py
MainFrame/Payroll/payroll_functions/payaddEmpFunction.py
MainFrame/Payroll/paytimeSheet/paytimeSheet.py
MainFrame/Resources/UI/employeeList_Accountant.ui
MainFrame/main_functions.py
MainWindow.py

We're using the add_employee_to_database to add the employee from the queue of notification then remove them into the queue
remove_employee_notification function, we will remove via empl_id
reorder_notification function, since we need to reorder the function for the indicationLbl that can be seen in paytimesheet UI.

Pay add employee for notification

---

MainFrame/Resources/UI/timecard.ui
MainFrame/TimeKeeping/timeCardMaker/timeCard.py
MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py

Import functionality in Timecard (Failed to make it work)
- This method imports .dat files by reading the file line by line, parsing fields, and merging the data with existing records using `update_time_list_table`.
- Here it updates `self.parent.original_data` with imported data by looking up existing entries, merging new data, and then calling `update_database` to persist the changes.
- Down to the database with new data by connecting to it, using an SQL statement to either update existing records or insert new ones based on `bioNum` and `trans_date`, and modifies fields such as `mach_code`, `time_in`, `time_out`, and `schedule`.

TimeCardDatImporter

---

MainFrame/TimeKeeping/timeCardMaker/timeCard.py
MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py
MainFrame/notificationMaker.py

Revise an entire code from Jhau-Em for the import function inside of the timecard
After a successful import a DAT file in database table, we just emitting a signal back into class populateList from timecardFunctions.py

Import dat functions for timecard

---

MainFrame/FILE201/Other_Information/otherInformationModal.py
MainFrame/Payroll/paymaster_Employee/payaddEmployee.py
MainFrame/Payroll/payroll_functions/deductionFunctions.py
MainFrame/Resources/UI/Schedule.ui
MainFrame/TimeKeeping/schedValidator/checkSched.py
MainFrame/systemFunctions.py

Created Integer validation for specific inputs needed

---

MainFrame/FILE201/Other_Information/otherInformationModal.py
MainFrame/FILE201/file201_Function/listFunction.py
MainFrame/Resources/UI/personalInformation.ui

- Resolved the Employee information modal, we remove this UI components since we already deleted them.
self.sssTextEdit, self.pagibigTextEdit, self.philHealthTextEdit, self.tinTextEdit
- UI Adjustments within the Employee information

Resolved employee information modal

---

MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py
MainFrame/notificationMaker.py

- Instead of passing the "N/A" when there's no found the program are sending "00:00:00" which can be a time format
NOTE: I'm still not sure if it's 12MD or what.

Processed PayTime sheet working

---

MainFrame/Resources/UI/timecard.ui
MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py
MainFrame/systemFunctions.py
System validation before dry run.txt

- The image above is how we're creating the ComboBox with the data of sched_in and sched_out from POSNSCHED table.
- We're using a 15mins interval since we want to create as much as possible optimize and make it efficient.
- Then we're determining the position of where we're gonna place the ComboBox which will be in index 6 and 7 of the table named Time_In and Time_Out.
- Since we're populating it to 24hours format hh:mm:ss then the date we have is just hh:mm we truncate the 3 symbols from the 24hours format it should be now hh:mm only.
When it comes of an efficient and effective solution for populating the table instead of redoing the population we just count the existing length of the table then add the new ones
**NOTE:** I Think it's very efficient.
- Overall we removed the code of the …

ComboBox implemented timecard

---

MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py
MainFrame/notificationMaker.py
System validation before dry run.txt

Timekeeper ND and NDOT Computation

---

MainFrame/TimeKeeping/timeSheet/timeSheet.py
MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py
MainFrame/notificationMaker.py

We need to validate the computation of ND and NDOT since we're not sure for the data we're getting.
But basically when getting the ND we're comparing the Check_In column data cell if it's target the after 9PM OR after 10PM if true it's just computing it until 12MN,
Then after 12MN there's a another computation 1AM until 6AM since we need to build up the 8Hrs working hours.
This is also why we cannot combine the Check_In and Check_Out value only if the Check_Out for that Check_In is in another day it will partner by 00:00:00 vice versa with Check_Out if there's no Check_In.
The Code below handles how it checks the Check_In using a time() function if it's a greater than nd_start if yes it will start checking the right formula to use.
We define also the value we comparing for the Check_In …

ND and NDOT Computation for validation

---

MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py
MainFrame/notificationMaker.py

- TimeCard functionality finalization of functions, but there's a problem where the time_out data should be time_out but instead it's been process on time_in since the Employee mistaken the input.
- The code above shows how the process of dat file processing into timecard.
- We also added a array for code 2 since in attlog_Admin the middle part which is code 2 is 0 and 1.
- We also determining if the Time_In or Time_Out is already existing, if true it should be updated with latest Time_In or Time_Out but it's verifying by date since some data should be partner while DAT file is on process.
- We're comparing the Check_In and Check_Out in this
So that we're getting the NDHours and NDOTHours, so we're already computing the Total days present/work, Total Hours work, NDhours, and NDOTHours. …

Time Card ND and NDOT Hours working

---

MainFrame/Database_Connection/modalSQLQuery.py
MainFrame/Database_Connection/user_auth.py
MainFrame/Payroll/payroll_functions/paytimeSheetFunctions.py
MainFrame/Payroll/paytimeSheet/paytimeSheet.py
System validation before dry run.txt

- The data validation function was updated to retain the original check for empty or insufficient rows while adding logging to track early exits, ensuring the table isn't populated without adequate data.

FixedTableRows

---

MainFrame/Payroll/payroll_functions/payComputations.py
MainFrame/Payroll/payroll_functions/payTransFunctions.py
MainFrame/Payroll/payroll_functions/paytimeSheetFunctions.py
MainFrame/Resources/UI/paytimesheet.ui
MainFrame/Resources/UI/paytrans.ui
MainFrame/systemFunctions.py

- Added HolidayND and RestDayND Computation
- Fix the computation within undertime, late, and regular night diff
- Added new columns in paytimesheet ui namely: RestdayNightOT, HolidayNightOT, and RestHolidayNightOT
- Added new columns in paytrans ui namely: RestDayNDOT_Earn, HolidayNDOT_Earn, RestHoli_Earn, RestHoliOT_Earn, RestHoliND_Earn, and RestHoliNDOT

Added HolidayND, and RestDayND Computation

---

MainFrame/Payroll/payroll_functions/payComputations.py
MainFrame/Payroll/payroll_functions/payTransFunctions.py
MainFrame/Payroll/payroll_functions/paytimeSheetFunctions.py

Added new computations in payComputations.py for:
- Rest Day Night Differential Overtime
- Holiday Night Differential Overtime
- Rest Day Holiday
- Rest Day Holiday Overtime
- Rest Day Holiday Night Differential
- Rest Day Holiday Night Differential Overtime
Population of the computation data list above is already been added within paytrans table
NOTE: The following Computation is still subject for validation since there are no existing data from the company for it to compare.

Added Computations for RDNDOT, HDNDOT, RH, RHOT, RHND, and RHNDOT

---

MainFrame/Resources/UI/TimeSheet.ui
MainFrame/TimeKeeping/timeSheet/timeSheet.py
MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py
MainFrame/systemFunctions.py

TO BE REVISE SPECIALLY TO TIMECARD SINCE IT'S NEED TO BE HAVE A DESIGN

EXCEL EXPORTER FOR TIMECARD AND TIMESHEET WORKING!!

---

MainFrame/Payroll/payroll_functions/paytimeSheetFunctions.py
MainFrame/Payroll/paytimeSheet/paytimeSheet.py
MainFrame/TimeKeeping/timeCardMaker/timeCard.py
MainFrame/systemFunctions.py

In paytimesheet it has a separate searchBioNum function because the bionum of the timekeeper and the payroll is not the same, so I add a method in paytimesheetFunctions.
Retrieves the text from the search field and normalizes it by stripping spaces and converting it to lowercase:
Checks if the BioNum in the current row contains the search text. If it does, the row is shown, otherwise, it's hidden.

SearchBioNumFunctions

---

MainFrame/Payroll/payroll_functions/payTransFunctions.py

- in the exporte_to_excel function the basis of the contents in excel exporter will now depend on payTransTable instead of the parent.data

Fixed Paytrans Exporter

---

MainFrame/Payroll/payroll_functions/deductionFunctions.py
MainFrame/Payroll/payroll_functions/payComputations.py
MainFrame/Payroll/paytimeSheet/storeDeductionLoader.py
MainFrame/Resources/UI/deduction.ui
MainFrame/Resources/UI/payDeduction.ui

ADDED OTHER (+)
ADDED A NEW COLUMN WHEN CREATING DEDUCTION
NOTE: "ONLY FOR SPECIFIC ID GONNA UPDATE" Still doesn't implemented, antok na.

ADDED OTHER (+)

---

MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py

•  Workbook(): Creates a new Excel workbook.
•  wb.active: Gets the active worksheet in the workbook.
•  ws.title: Sets the title of the worksheet to "Timecard Data
The comboBox string is converted into integer to make the header date static
Iterates through `date_range`, formats each date as "01-Aug", retrieves the abbreviated day name (e.g., "THU"), and appends both to their respective lists.
Column mapping and populate the corresponding item
Iterates through all rows in the worksheet and applies center alignment to each cell.

TimeCardExport

---

MainFrame/Database_Connection/DBConnection.py
MainFrame/Database_Connection/modalSQLQuery.py
MainFrame/Database_Connection/notification_listener.py
MainFrame/Database_Connection/user_auth.py
MainFrame/Database_Connection/user_session.py
MainFrame/FILE201/Employee_List/employeeList.py
MainFrame/FILE201/Other_Information/otherInformationModal.py
MainFrame/FILE201/file201_Function/excelExport.py
MainFrame/FILE201/file201_Function/excelImporter.py
MainFrame/FILE201/file201_Function/listFunction.py
MainFrame/FILE201/file201_Function/modalFunction.py
MainFrame/FILE201/file201_Function/pieGraph.py
MainFrame/Resources/lib.py
MainFrame/TimeKeeping/datImporter/dialogLoader.py
MainFrame/TimeKeeping/dateChange/dateChange.py
MainFrame/TimeKeeping/schedValidator/checkSched.py
MainFrame/TimeKeeping/timeCardMaker/filter.py
MainFrame/TimeKeeping/timeCardMaker/timeCard.py
MainFrame/TimeKeeping/timeSheet/timeSheet.py
MainFrame/TimeKeeping/timekeeper_functions/dialogFunctions.py
MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py
MainFrame/bugReport.py
MainFrame/fontLoader.py
MainFrame/main_functions.py
MainFrame/notificationMaker.py
MainFrame/systemFunctions.py
MainWindow.py

- Replaced QMessageBox errors instead of using loggers.
- Removed unnecessary libraries and frameworks.
- The only area I didn't fix is Payroll.

TryCatchErrors

---

.idea/misc.xml
.idea/systemPayroll.iml
MainFrame/Payroll/payTrans/bankRegister.py
MainFrame/Payroll/payroll_functions/bankRegisterFunctions.py
MainFrame/Payroll/payroll_functions/payComputations.py
MainFrame/Payroll/payroll_functions/payTransFunctions.py
MainFrame/Payroll/payroll_functions/paytimeSheetFunctions.py
MainFrame/Resources/UI/paytrans.ui

- Set tooltip in Employee Name column in paytimesheet, paytrans, and bankregister
- Fixed Search Bionum in bankregister
- Added OrdDay_Earn column and rename some columns in payTrans.ui
- Added regularDayEarnComputation in payComputations that adds the regular/ordinary day earnings of each employee
- Added calculateGrossPay in bankRegisterFunctions.py that will adds gross pay for each employee data
- Added getGrandTotal that retrieves the grand total of all the net pay data
NOTE: I used the gross pay that for net pay value tentatively, since there is no deduction data yet in our system. Also in regularDayEarnComputation, it supposed to be calculated with ordinary day hours not with days work.

Added Grandtotal and Netpay column values in bankRegister

---

MainFrame/Payroll/payTrans/bankRegister.py
MainFrame/Payroll/payroll_functions/bankRegisterFunctions.py
MainFrame/Payroll/payroll_functions/payTransFunctions.py
MainFrame/Resources/UI/bankregister.ui
MainFrame/Resources/UI/paytrans.ui
MainFrame/Resources/lib.py

- Added a export to excel button in bankregister.ui
- Added exportBankRegisterToExcel function in bankRegisterFunctions.py that gives functionality to export to excel button to save the bank register data into excel file format
- Imported new module called 'xlswriter', this module can modify the format of an excel

Added Excel Exporter feature to BankRegister

---

MainFrame/FILE201/file201_Function/excelImporter.py
MainFrame/Payroll/payroll_functions/deductionFunctions.py
MainFrame/Payroll/paytimeSheet/storeDeductionLoader.py
MainFrame/Resources/UI/payDeduction.ui

- The query for storing deduction is update/added a query function that will check if it's greater than 0 update the data then if there's a updated input from the UI it will check/compare the data then it will update that value.
- Excel importer in HR will is not done.

Storing deduction issue fixed

---

MainFrame/Resources/UI/Schedule.ui
MainFrame/TimeKeeping/schedValidator/schedule.py
MainFrame/TimeKeeping/timeCardMaker/timeCard.py
MainFrame/TimeKeeping/timekeeper_functions/timecardFunctions.py

- In timecard.py, I set btnCheckSched.setVisible(True) to display the "Check Schedule" button.
- Redesigned the schedule UI with a new layout, added a new Python file, and reused the functions from checkSched. Also added an employee table that displays details when a row is selected (though currently only the bioNum and empName are being fetched), and empty as return.

NewScheduleFunction

---

MainFrame/Payroll/payTrans/payTransLoader.py
MainFrame/Payroll/payroll_functions/bankRegisterFunctions.py
MainFrame/Payroll/payroll_functions/deductionFunctions.py
MainFrame/Payroll/payroll_functions/payComputations.py
MainFrame/Payroll/payroll_functions/payTransFunctions.py
MainFrame/Payroll/payroll_functions/paytimeSheetFunctions.py
MainFrame/Payroll/paytimeSheet/storeDeductionLoader.py
MainFrame/Resources/UI/deduction.ui
MainFrame/Resources/UI/payDeduction.ui
MainFrame/Resources/UI/paytrans.ui

**deductions table in ntp_stored_deductions:**
- remove columns: sss, pagibig, and philheath in deductions database
**PayComputation.py**
- Added a new class named "PayContributions" which handles all SSS, PhilHealth, and Pag-IBIG contribution calculation methods
**PayTrans**
- Added new button in Paytrans namely: "Calculate Deductions" in which calculates all the contributions of employees per cut off based on their gross income
- Added new column named Gross_Income in paytransTable
**Paymaster2 Table**
- remove columns: sss, pagibig, and medicare/philheath 
- remove input fields in edit payables modal namely: sss, pagibig, and medicare/philheath

Added Contribution/Deduction Calculation

---

MainFrame/Payroll/payTrans/payTransMailer.py
MainFrame/Payroll/payroll_functions/payTransFunctions.py

**Paytrans Functions**
- Adjusted the required columns for importing excel deduction based on the new one.
**PayTransMailer**
- Redesigned the email structure for payTransMailer.
- Added some dynamic data within the email

Redesigned Email Structure

---

MainFrame/Payroll/payroll_functions/payComputations.py
MainFrame/Payroll/payroll_functions/payTransFunctions.py
MainFrame/Payroll/payroll_functions/paytimeSheetFunctions.py

- Refractor the updated key and value pairs of column_names within PayComputation and payTimeSheetFunctions

Bugged Fixed: Populating Paytrans Table

---

MainFrame/Payroll/payroll_functions/payViewListFunctions.py

**Features**
Double-click to edit any cell in columns 3–11 (RPH → Pag-Ibig Amount).
Integer validation (via ValidInteger class) to restrict input to numbers.
Real-time database sync for database-backed fields (e.g., rph, rate).
Non-database fields (e.g., Basic, SSS Loaned) update only the UI/data structure.
User feedback with success/error messages.
<html>
<body>
Method | Description
-- | --
setup_double_click_handler | Connects the table's cellDoubleClicked signal to the handler.
handle_cell_double_click | Replaces cell with a QLineEdit on double-click (columns 3–11 only).
handle_edit_finished | Saves edits to UI/data structure and triggers DB update.
update_database_value | Executes SQL UPDATE for database-backed columns.
get_column_name | Maps table column indices to database field …

Created a Function for Salary Editing Cell
